/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Înregistrare utilizator nou
         * @description Creează un nou cont de utilizator cu email și parolă. Parola este hash-uită înainte de a fi salvată în baza de date. Refresh token-ul este setat în cookie.
         */
        post: operations["AuthController_register"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/auth/login": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Autentificare utilizator
         * @description Autentifică un utilizator existent folosind email și parolă. Returnează access token în body și refresh token în cookie.
         */
        post: operations["AuthController_login"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/auth/refresh": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Reînnoire access token
         * @description Reînnoiește access token-ul folosind refresh token-ul din cookie (OBLIGATORIU). Refresh token-ul este securizat și trimis DOAR în cookie. Returnează un nou access token în body și actualizează refresh token-ul în cookie.
         */
        post: operations["AuthController_refresh"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/auth/logout": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Deconectare utilizator
         * @description Deconectează utilizatorul autentificat prin ștergerea cookie-ului cu refresh token. Access token-ul rămâne valid până la expirare, dar refresh token-ul este invalidat.
         */
        post: operations["AuthController_logout"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/auth/me": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Preluare date utilizator curent
         * @description Returnează datele utilizatorului autentificat pe baza token-ului JWT din header.
         */
        get: operations["AuthController_getMe"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/auth/profile": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        /**
         * Actualizare profil utilizator
         * @description Actualizează datele profilului utilizatorului autentificat. Toate câmpurile sunt opționale - poți actualiza doar ceea ce dorești (firstName, lastName, profileImage). Imaginea de profil va fi uploadată în Cloudinary.
         */
        patch: operations["AuthController_updateProfile"]
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        ErrorResponseDto: {
            /**
             * @description Codul de status HTTP al erorii
             * @example 400
             */
            statusCode: number
            /**
             * @description Mesajul de eroare sau array de mesaje de validare
             * @example Email-ul este deja înregistrat
             */
            message: string | string[]
            /**
             * @description Numele erorii (ex: Bad Request, Not Found, Conflict)
             * @example Bad Request
             */
            error: string
        }
        UserResponseDto: {
            /**
             * @description ID-ul unic al utilizatorului
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string
            /**
             * @description Numele utilizatorului
             * @example John
             */
            firstName?: string
            /**
             * @description Prenumele utilizatorului
             * @example Doe
             */
            lastName?: string
            /**
             * @description URL-ul imaginii de profil
             * @example https://example.com/profile.jpg
             */
            profileImage?: string
            /**
             * @description Rolul utilizatorului în sistem
             * @example USER
             * @enum {string}
             */
            rol: "USER" | "ADMIN"
            /**
             * @description Data și ora creării contului (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string
            /**
             * @description Data și ora ultimei actualizări (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            updatedAt: string
        }
        AuthResponseDto: {
            /**
             * @description Access token JWT pentru autentificare (trimis în body)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            accessToken: string
            /** @description Datele utilizatorului autentificat */
            user: components["schemas"]["UserResponseDto"]
        }
        UpdateProfileDto: {
            /**
             * @description Numele utilizatorului
             * @example John
             */
            firstName?: string
            /**
             * @description Prenumele utilizatorului
             * @example Doe
             */
            lastName?: string
        }
        RegisterDto: {
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string
            /**
             * @description Parola utilizatorului (minim 8 caractere, cel puțin o literă mare, o literă mică, o cifră și un caracter special)
             * @example SecurePassword123!
             */
            password: string
        }
        LoginDto: {
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string
            /**
             * @description Parola utilizatorului
             * @example SecurePassword123!
             */
            password: string
        }
    }
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"]
            }
        }
        responses: {
            /** @description Utilizator creat cu succes */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: components["schemas"]["AuthResponseDto"]
                    }
                }
            }
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "email must be an email",
             *         "password must be longer than or equal to 8 characters"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "email must be an email",
                     *         "password must be longer than or equal to 8 characters"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
            /**
             * @description Email-ul este deja înregistrat
             * @example {
             *       "statusCode": 409,
             *       "message": "Email-ul este deja înregistrat",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "Email-ul este deja înregistrat",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
    AuthController_login: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"]
            }
        }
        responses: {
            /** @description Autentificare reușită */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: components["schemas"]["AuthResponseDto"]
                    }
                }
            }
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "email must be an email",
             *         "password should not be empty"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "email must be an email",
                     *         "password should not be empty"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
            /**
             * @description Email sau parolă incorectă
             * @example {
             *       "statusCode": 401,
             *       "message": "Email sau parolă incorectă",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Email sau parolă incorectă",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
    AuthController_refresh: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Access token reînnoit cu succes */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: {
                            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                            accessToken?: string
                        }
                    }
                }
            }
            /**
             * @description Refresh token invalid, expirat sau lipsă din cookie
             * @example {
             *       "statusCode": 401,
             *       "message": "Refresh token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Refresh token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
    AuthController_logout: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Deconectare reușită */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: {
                            /** @example Deconectare reușită */
                            message?: string
                        }
                    }
                }
            }
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
    AuthController_getMe: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Date utilizator returnate cu succes */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: components["schemas"]["UserResponseDto"]
                    }
                }
            }
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
    AuthController_updateProfile: {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description Numele utilizatorului
                     * @example John
                     */
                    firstName?: string
                    /**
                     * @description Prenumele utilizatorului
                     * @example Doe
                     */
                    lastName?: string
                    /**
                     * Format: binary
                     * @description Imaginea de profil (JPG, PNG, max 5MB)
                     */
                    profileImage?: string
                }
            }
        }
        responses: {
            /** @description Profil actualizat cu succes */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": {
                        data?: components["schemas"]["UserResponseDto"]
                    }
                }
            }
            /**
             * @description Date de validare invalide sau eroare la upload-ul imaginii
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "firstName must be longer than or equal to 2 characters",
             *         "Dimensiunea fișierului nu poate depăși 5MB"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "firstName must be longer than or equal to 2 characters",
                     *         "Dimensiunea fișierului nu poate depăși 5MB"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"]
                }
            }
        }
    }
}
