/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Înregistrare utilizator nou
         * @description Creează un nou cont de utilizator cu email și parolă. Parola este hash-uită înainte de a fi salvată în baza de date. Refresh token-ul este setat în cookie.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autentificare utilizator
         * @description Autentifică un utilizator existent folosind email și parolă. Returnează access token în body și refresh token în cookie.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reînnoire access token
         * @description Reînnoiește access token-ul folosind refresh token-ul din cookie (OBLIGATORIU). Refresh token-ul este securizat și trimis DOAR în cookie. Returnează un nou access token în body și actualizează refresh token-ul în cookie.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deconectare utilizator
         * @description Deconectează utilizatorul autentificat prin ștergerea cookie-ului cu refresh token. Access token-ul rămâne valid până la expirare, dar refresh token-ul este invalidat.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preluare date utilizator curent
         * @description Returnează datele utilizatorului autentificat pe baza token-ului JWT din header.
         */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizare profil utilizator
         * @description Actualizează datele profilului utilizatorului autentificat. Toate câmpurile sunt opționale - poți actualiza doar ceea ce dorești (firstName, lastName, profileImage). Imaginea de profil va fi uploadată în Cloudinary.
         */
        patch: operations["AuthController_updateProfile"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista categorii
         * @description Returnează toate categoriile. Rută publică – nu necesită autentificare.
         */
        get: operations["CategoryController_findAll"];
        put?: never;
        /**
         * Creare categorie
         * @description Creează o categorie nouă. Slug-ul trebuie să fie unic.
         */
        post: operations["CategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalii categorie
         * @description Returnează o categorie după ID. Rută publică – nu necesită autentificare.
         */
        get: operations["CategoryController_findOne"];
        put?: never;
        post?: never;
        /**
         * Ștergere categorie
         * @description Șterge o categorie. Versiune de test – poate fi refăcută ulterior cu soft delete.
         */
        delete: operations["CategoryController_remove"];
        options?: never;
        head?: never;
        /**
         * Actualizare categorie
         * @description Actualizează o categorie existentă. Toate câmpurile sunt opționale.
         */
        patch: operations["CategoryController_update"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista produse
         * @description Returnează lista de produse cu suport pentru filtrare și paginare. Poți filtra după categoryId, types, ingredients, sizes. Rută publică – nu necesită autentificare.
         */
        get: operations["ProductController_findAll"];
        put?: never;
        /**
         * Creare produs
         * @description Creează un produs nou. Slug-ul trebuie să fie unic. Categoria trebuie să existe.
         */
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filtre disponibile pentru produse
         * @description Fără categoryId: returnează filtrele pentru toate produsele ACTIVE. Cu categoryId: returnează filtrele doar pentru produsele ACTIVE din categoria respectivă. Status nu este expus în filtre (doar produsele active sunt disponibile pentru client). Rută publică – nu necesită autentificare.
         */
        get: operations["ProductController_getFilters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalii produs
         * @description Returnează un produs după ID. Rută publică – nu necesită autentificare.
         */
        get: operations["ProductController_findOne"];
        put?: never;
        post?: never;
        /**
         * Ștergere produs
         * @description Șterge un produs.
         */
        delete: operations["ProductController_remove"];
        options?: never;
        head?: never;
        /**
         * Actualizare produs
         * @description Actualizează un produs existent. Toate câmpurile sunt opționale.
         */
        patch: operations["ProductController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponseDto: {
            /**
             * @description Codul de status HTTP al erorii
             * @example 400
             */
            statusCode: number;
            /**
             * @description Mesajul de eroare sau array de mesaje de validare
             * @example Email-ul este deja înregistrat
             */
            message: string | string[];
            /**
             * @description Numele erorii (ex: Bad Request, Not Found, Conflict)
             * @example Bad Request
             */
            error: string;
        };
        UserResponseDto: {
            /**
             * @description ID-ul unic al utilizatorului
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Numele utilizatorului
             * @example John
             */
            firstName: string | null;
            /**
             * @description Prenumele utilizatorului
             * @example Doe
             */
            lastName: string | null;
            /**
             * @description URL-ul imaginii de profil
             * @example https://example.com/profile.jpg
             */
            profileImage: string | null;
            /**
             * @description Rolul utilizatorului în sistem
             * @example USER
             * @enum {string}
             */
            rol: "USER" | "ADMIN";
            /**
             * @description Data și ora creării contului (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * @description Data și ora ultimei actualizări (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            updatedAt: string;
        };
        AuthResponseDto: {
            /**
             * @description Access token JWT pentru autentificare (trimis în body)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
             */
            accessToken: string;
            /** @description Datele utilizatorului autentificat */
            user: components["schemas"]["UserResponseDto"];
        };
        UpdateProfileDto: {
            /**
             * @description Numele utilizatorului
             * @example John
             */
            firstName?: string;
            /**
             * @description Prenumele utilizatorului
             * @example Doe
             */
            lastName?: string;
        };
        RegisterDto: {
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Parola utilizatorului (minim 8 caractere, cel puțin o literă mare, o literă mică, o cifră și un caracter special)
             * @example SecurePassword123!
             */
            password: string;
        };
        LoginDto: {
            /**
             * @description Adresa de email a utilizatorului
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Parola utilizatorului
             * @example SecurePassword123!
             */
            password: string;
        };
        CategoryResponseDto: {
            /**
             * @description ID-ul unic al categoriei
             * @example 1
             */
            id: number;
            /**
             * @description Slug-ul unic al categoriei (URL-friendly)
             * @example pizza-clasica
             */
            slug: string;
            /**
             * @description Numele categoriei
             * @example Pizza Clasică
             */
            name: string;
            /**
             * @description Statutul categoriei (activ/inactiv)
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description Data și ora creării (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * @description Data și ora ultimei actualizări (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            updatedAt: string;
        };
        CreateCategoryDto: {
            /**
             * @description Identificator unic URL-friendly pentru categorie (kebab-case)
             * @example pizza-clasica
             */
            slug: string;
            /**
             * @description Numele afișat al categoriei
             * @example Pizza Clasică
             */
            name: string;
            /**
             * @description Statutul categoriei (activ/inactiv). Implicit: ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        UpdateCategoryDto: {
            /**
             * @description Identificator unic URL-friendly pentru categorie (kebab-case)
             * @example pizza-clasica
             */
            slug?: string;
            /**
             * @description Numele afișat al categoriei
             * @example Pizza Clasică
             */
            name?: string;
            /**
             * @description Statutul categoriei (activ/inactiv)
             * @example INACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
        };
        ProductResponseDto: {
            /**
             * @description ID-ul unic al produsului
             * @example 1
             */
            id: number;
            /**
             * @description Slug-ul unic al produsului (URL-friendly)
             * @example margherita
             */
            slug: string;
            /**
             * @description Numele produsului
             * @example Pizza Margherita
             */
            name: string;
            /**
             * @description Descrierea produsului
             * @example Pizza clasică cu roșii și mozzarella
             */
            description: string | null;
            /**
             * @description Prețul produsului
             * @example 24.99
             */
            price: number;
            /**
             * @description URL-ul imaginii produsului
             * @example https://example.com/images/margherita.jpg
             */
            imageUrl: string | null;
            /**
             * @description Tipul produsului
             * @example SIMPLE
             * @enum {string}
             */
            type: "SIMPLE" | "CONFIGURABLE";
            /**
             * @description Statutul produsului (activ/inactiv)
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /**
             * @description ID-ul categoriei
             * @example 1
             */
            categoryId: number;
            /** @description Categoria produsului */
            category: components["schemas"]["CategoryResponseDto"] | null;
            /**
             * @description Lista de ingrediente
             * @example [
             *       "roșii",
             *       "mozzarella",
             *       "busuioc"
             *     ]
             */
            ingredients: string[];
            /**
             * @description Lista de mărimi disponibile
             * @example [
             *       "mică",
             *       "medie",
             *       "mare"
             *     ]
             */
            sizes: string[];
            /**
             * @description Data și ora creării (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * @description Data și ora ultimei actualizări (format ISO 8601)
             * @example 2024-01-15T10:30:00.000Z
             */
            updatedAt: string;
        };
        PaginatedMetaDto: {
            /**
             * @description Numărul total de înregistrări care corespund filtrelor
             * @example 50
             */
            total: number;
            /**
             * @description Numărul paginii curente
             * @example 1
             */
            page: number;
            /**
             * @description Numărul de înregistrări per pagină
             * @example 10
             */
            limit: number;
        };
        ProductListResponseDto: {
            /** @description Lista de produse */
            data: components["schemas"]["ProductResponseDto"][];
            /** @description Meta-informații pentru paginare */
            meta: components["schemas"]["PaginatedMetaDto"];
        };
        FilterOptionDto: {
            /**
             * @description Valoarea tehnică a filtrului (trimisă la server)
             * @example CONFIGURABLE
             */
            id: string;
            /**
             * @description Eticheta formatată pentru afișare în UI
             * @example Personalizabil
             */
            name: string;
        };
        ProductFiltersResponseDto: {
            /**
             * @description Tipuri de produse disponibile (SIMPLE/CONFIGURABLE)
             * @example [
             *       {
             *         "id": "SIMPLE",
             *         "name": "Simplu"
             *       },
             *       {
             *         "id": "CONFIGURABLE",
             *         "name": "Personalizabil"
             *       }
             *     ]
             */
            types: components["schemas"]["FilterOptionDto"][];
            /**
             * @description Ingrediente disponibile în produsele filtrate
             * @example [
             *       {
             *         "id": "roșii",
             *         "name": "Roșii"
             *       },
             *       {
             *         "id": "mozzarella",
             *         "name": "Mozzarella"
             *       },
             *       {
             *         "id": "busuioc",
             *         "name": "Busuioc"
             *       }
             *     ]
             */
            ingredients: components["schemas"]["FilterOptionDto"][];
            /**
             * @description Mărimi disponibile în produsele filtrate
             * @example [
             *       {
             *         "id": "mică",
             *         "name": "Mică"
             *       },
             *       {
             *         "id": "medie",
             *         "name": "Medie"
             *       },
             *       {
             *         "id": "mare",
             *         "name": "Mare"
             *       }
             *     ]
             */
            sizes: components["schemas"]["FilterOptionDto"][];
        };
        CreateProductDto: {
            /**
             * @description Identificator unic URL-friendly pentru produs (kebab-case)
             * @example margherita
             */
            slug: string;
            /**
             * @description Numele afișat al produsului
             * @example Pizza Margherita
             */
            name: string;
            /**
             * @description Descrierea produsului
             * @example Pizza clasică cu roșii și mozzarella
             */
            description?: string;
            /**
             * @description Prețul produsului
             * @example 24.99
             */
            price: number;
            /**
             * @description URL-ul imaginii produsului
             * @example https://example.com/images/margherita.jpg
             */
            imageUrl?: string;
            /**
             * @description Tipul produsului. Implicit: SIMPLE
             * @example SIMPLE
             * @enum {string}
             */
            type?: "SIMPLE" | "CONFIGURABLE";
            /**
             * @description Statutul produsului (activ/inactiv). Implicit: ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
            /**
             * @description ID-ul categoriei căreia îi aparține produsul
             * @example 1
             */
            categoryId: number;
            /**
             * @description Lista de ingrediente
             * @example [
             *       "roșii",
             *       "mozzarella",
             *       "busuioc"
             *     ]
             */
            ingredients?: string[];
            /**
             * @description Lista de mărimi disponibile
             * @example [
             *       "mică",
             *       "medie",
             *       "mare"
             *     ]
             */
            sizes?: string[];
        };
        UpdateProductDto: {
            /**
             * @description Identificator unic URL-friendly pentru produs (kebab-case)
             * @example margherita
             */
            slug?: string;
            /**
             * @description Numele afișat al produsului
             * @example Pizza Margherita
             */
            name?: string;
            /**
             * @description Descrierea produsului
             * @example Pizza clasică cu roșii și mozzarella
             */
            description?: string;
            /**
             * @description Prețul produsului
             * @example 24.99
             */
            price?: number;
            /**
             * @description URL-ul imaginii produsului
             * @example https://example.com/images/margherita.jpg
             */
            imageUrl?: string;
            /**
             * @description Tipul produsului. Implicit: SIMPLE
             * @example SIMPLE
             * @enum {string}
             */
            type?: "SIMPLE" | "CONFIGURABLE";
            /**
             * @description Statutul produsului (activ/inactiv). Implicit: ACTIVE
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE";
            /**
             * @description ID-ul categoriei căreia îi aparține produsul
             * @example 1
             */
            categoryId?: number;
            /**
             * @description Lista de ingrediente
             * @example [
             *       "roșii",
             *       "mozzarella",
             *       "busuioc"
             *     ]
             */
            ingredients?: string[];
            /**
             * @description Lista de mărimi disponibile
             * @example [
             *       "mică",
             *       "medie",
             *       "mare"
             *     ]
             */
            sizes?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Utilizator creat cu succes */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "email must be an email",
             *         "password must be longer than or equal to 8 characters"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "email must be an email",
                     *         "password must be longer than or equal to 8 characters"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Email-ul este deja înregistrat
             * @example {
             *       "statusCode": 409,
             *       "message": "Email-ul este deja înregistrat",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "Email-ul este deja înregistrat",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Autentificare reușită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "email must be an email",
             *         "password should not be empty"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "email must be an email",
                     *         "password should not be empty"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Email sau parolă incorectă
             * @example {
             *       "statusCode": 401,
             *       "message": "Email sau parolă incorectă",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Email sau parolă incorectă",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access token reînnoit cu succes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                            accessToken: string;
                        };
                    };
                };
            };
            /**
             * @description Refresh token invalid, expirat sau lipsă din cookie
             * @example {
             *       "statusCode": 401,
             *       "message": "Refresh token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Refresh token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deconectare reușită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @example Deconectare reușită */
                            message: string;
                        };
                    };
                };
            };
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Date utilizator returnate cu succes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResponseDto"];
                    };
                };
            };
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * @description Numele utilizatorului
                     * @example John
                     */
                    firstName?: string;
                    /**
                     * @description Prenumele utilizatorului
                     * @example Doe
                     */
                    lastName?: string;
                    /**
                     * Format: binary
                     * @description Imaginea de profil (JPG, PNG, max 5MB)
                     */
                    profileImage?: string;
                };
            };
        };
        responses: {
            /** @description Profil actualizat cu succes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide sau eroare la upload-ul imaginii
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "firstName must be longer than or equal to 2 characters",
             *         "Dimensiunea fișierului nu poate depăși 5MB"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "firstName must be longer than or equal to 2 characters",
                     *         "Dimensiunea fișierului nu poate depăși 5MB"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Neautorizat - Token invalid sau lipsă
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoryController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorii */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResponseDto"][];
                    };
                };
            };
        };
    };
    CategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Categoria a fost creată */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "slug must match the following pattern...",
             *         "name must be longer than or equal to 2 characters"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "slug must match the following pattern...",
                     *         "name must be longer than or equal to 2 characters"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot crea categorii
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Slug-ul există deja
             * @example {
             *       "statusCode": 409,
             *       "message": "O categorie cu slug-ul \"pizza-clasica\" există deja",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "O categorie cu slug-ul \"pizza-clasica\" există deja",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoryController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria a fost găsită */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResponseDto"];
                    };
                };
            };
            /**
             * @description Categoria nu a fost găsită
             * @example {
             *       "statusCode": 404,
             *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria a fost ștearsă */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot șterge categorii
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Categoria nu a fost găsită
             * @example {
             *       "statusCode": 404,
             *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Categoria a fost actualizată */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CategoryResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "slug must match the following pattern..."
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "slug must match the following pattern..."
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot actualiza categorii
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Categoria nu a fost găsită
             * @example {
             *       "statusCode": 404,
             *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Slug-ul există deja
             * @example {
             *       "statusCode": 409,
             *       "message": "O categorie cu slug-ul \"pizza-clasica\" există deja",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "O categorie cu slug-ul \"pizza-clasica\" există deja",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_findAll: {
        parameters: {
            query?: {
                /** @description Opțional. Dacă lipsește – toate produsele. Dacă este indicat – doar produsele din acea categorie. */
                categoryId?: number;
                /** @description Opțional. Numărul paginii (default: 1). Minim: 1. */
                page?: number;
                /** @description Opțional. Numărul de produse per pagină (default: 10). Minim: 1, Maxim: 100. */
                limit?: number;
                /** @description Opțional. Array de mărimi pentru filtrare. Exemplu: ?sizes=mică&sizes=medie */
                sizes?: unknown[];
                /** @description Opțional. Array de ingrediente pentru filtrare. Exemplu: ?ingredients=roșii&ingredients=mozzarella */
                ingredients?: unknown[];
                /** @description Opțional. Array de tipuri de produse pentru filtrare. Valori posibile: SIMPLE, CONFIGURABLE. Exemplu: ?types=SIMPLE&types=CONFIGURABLE */
                types?: unknown[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de produse cu meta informații pentru paginare */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponseDto"];
                };
            };
            /**
             * @description Parametri invalizi (categoryId, page sau limit nu sunt numere valide)
             * @example {
             *       "statusCode": 400,
             *       "message": "categoryId trebuie să fie un număr valid",
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": "categoryId trebuie să fie un număr valid",
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Categoria specificată nu a fost găsită
             * @example {
             *       "statusCode": 404,
             *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Produsul a fost creat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide sau categoria nu există
             * @example {
             *       "statusCode": 400,
             *       "message": [
             *         "price must be a positive number",
             *         "Categoria cu ID-ul 999 nu există"
             *       ],
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": [
                     *         "price must be a positive number",
                     *         "Categoria cu ID-ul 999 nu există"
                     *       ],
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot crea produse
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Slug-ul există deja
             * @example {
             *       "statusCode": 409,
             *       "message": "Un produs cu slug-ul \"margherita\" există deja",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "Un produs cu slug-ul \"margherita\" există deja",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_getFilters: {
        parameters: {
            query?: {
                /** @description Opțional. Dacă lipsește – filtre pentru toate produsele ACTIVE. Dacă este indicat – filtre doar pentru produsele ACTIVE din acea categorie. */
                categoryId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtrele disponibile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductFiltersResponseDto"];
                    };
                };
            };
            /**
             * @description categoryId invalid
             * @example {
             *       "statusCode": 400,
             *       "message": "categoryId trebuie să fie un număr valid",
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": "categoryId trebuie să fie un număr valid",
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Categoria specificată nu a fost găsită
             * @example {
             *       "statusCode": 404,
             *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Categoria cu ID-ul 999 nu a fost găsită",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produsul a fost găsit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResponseDto"];
                    };
                };
            };
            /**
             * @description Produsul nu a fost găsit
             * @example {
             *       "statusCode": 404,
             *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produsul a fost șters */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot șterge produse
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Produsul nu a fost găsit
             * @example {
             *       "statusCode": 404,
             *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProductController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Produsul a fost actualizat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResponseDto"];
                    };
                };
            };
            /**
             * @description Date de validare invalide sau categoria nu există
             * @example {
             *       "statusCode": 400,
             *       "message": "Categoria cu ID-ul 999 nu există",
             *       "error": "Bad Request"
             *     }
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 400,
                     *       "message": "Categoria cu ID-ul 999 nu există",
                     *       "error": "Bad Request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Neautorizat
             * @example {
             *       "statusCode": 401,
             *       "message": "Token invalid sau expirat",
             *       "error": "Unauthorized"
             *     }
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 401,
                     *       "message": "Token invalid sau expirat",
                     *       "error": "Unauthorized"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Doar administratorii pot actualiza produse
             * @example {
             *       "statusCode": 403,
             *       "message": "Doar administratorii pot efectua această acțiune",
             *       "error": "Forbidden"
             *     }
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 403,
                     *       "message": "Doar administratorii pot efectua această acțiune",
                     *       "error": "Forbidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Produsul nu a fost găsit
             * @example {
             *       "statusCode": 404,
             *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
             *       "error": "Not Found"
             *     }
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 404,
                     *       "message": "Produsul cu ID-ul 999 nu a fost găsit",
                     *       "error": "Not Found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /**
             * @description Slug-ul există deja
             * @example {
             *       "statusCode": 409,
             *       "message": "Un produs cu slug-ul \"margherita\" există deja",
             *       "error": "Conflict"
             *     }
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "statusCode": 409,
                     *       "message": "Un produs cu slug-ul \"margherita\" există deja",
                     *       "error": "Conflict"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
